name: Check

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup npm
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install npm packages
        run: npm install
      - name: Check Format
        run: npm run check-format
      - name: Test
        run: npm test
      - name: Build static files
        run: npm run build