name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup npm
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install npm packages
        run: npm install
      - name: Test
        run: npm test
      - name: Build static files
        run: npm run build
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist